### ISSUE TITLE
Allow projection change with ST_Transform

### ISSUE THREAD

**Issue by PanierAvide** [Esri/spatial-framework-for-hadoop#90] opened 2015-10-09 21:17 UTC
First of all, thanks for this useful framework. Currently, it doesn't support projection change, you can only change the SRID in metadata but it doesn't modify object coordinates in returned data. Adding a function with similar to ST_Transform in Postgis (see http://postgis.net/docs/ST_Transform.html) would be very useful, for example for creating buffers in a metric projection.

**Comment by randallwhitman** [comment] 2015-10-09 21:44
Cross-reference https://github.com/Esri/geometry-api-java/issues/64

**Comment by randallwhitman** [comment] 2015-12-11 16:52
[Reference to doc](https://github.com/Esri/spatial-framework-for-hadoop/wiki/ST_Geometry-in-Hive-versus-SQL#st_geometry-functions-not-supported-in-hive)

**Comment by randallwhitman** [comment] 2016-03-02 23:12
Maybe related: #83

**Comment by chaosmail** [comment] 2016-11-10 17:25
I would be also very interested in this feature, as well willing to help. I guess this could be implemented by adding an existing library for projections such as [proj4j](https://trac.osgeo.org/proj4j/) or [cts](https://github.com/orbisgis/cts). Are there any plans to support ST_Transform in the future?

**Comment by randallwhitman** [comment] 2016-11-10 19:45
> Are there any plans to support ST_Transform in the future?

We currently have no plans that I know of to work on that.

**Comment by randallwhitman** [comment] 2016-11-30 19:04
Cross-reference https://geonet.esri.com/thread/186465-geometry-vs-geography

**Comment by randallwhitman** [comment] 2018-07-11 21:11
Side note relating to above-referenced proj4j - the [Esri UC 2018 Q&A](https://www.esri.com/en-us/about/events/uc/get-involved/q-and-a#id=3089) states that Esri is "funding a portion of the work to enhance/update PROJ4" (under "What are Esri's contributions to the open source community?")

**Comment by randallwhitman** [comment] 2022-09-30 04:04
Discussion on #186 is more detailed, so I'll mark this one a duplicate of that one.

**Closed by randallwhitman** 2022-09-30 04:04 UTC
Labels: duplicate, enhancement
